### ISSUE TITLE
I'm getting these white bars in the top and bottom

### ISSUE THREAD

**Issue by LostConnection** [jszklarz-haventec/makeitdark#32]
Thanks for all your help on this. Crazy that Slack still hasn't done this themselves.

Got this to (mostly) work with @defmonk0's fix. But I'm getting these white bars in the top and bottom now:

![2019-07-25 21 25 39](https://user-images.githubusercontent.com/8637082/61919270-e3605180-af22-11e9-9668-04dd3a0ffb60.png)

_Originally posted by @yourfriendaaron in https://github.com/LostConnection/makeitdark/issues/27#issuecomment-515273435_

**Comment by LostConnection** [comment]
@yourfriendaaron I've addressed these issues and tested on a Windows machine. They're pushed to master.

**Comment by hioz12** [comment]
The only white section I am seeing is the search bar at the top right of the app. 
![2019-07-26_8-15-31](https://user-images.githubusercontent.com/35497308/61950990-95c50280-af7d-11e9-99a2-801c0519e57e.png)

**Comment by hioz12** [comment]
Thanks a lot of the updates man, you are saving my eyes

**Comment by yourfriendaaron** [comment]
![2019-07-26 10 39 45](https://user-images.githubusercontent.com/8637082/61959575-b303cc00-af91-11e9-8ff3-76e0b4ec9c3e.png)

Yup, I'm still seeing that, too. But other than that it's nearly back to the pre-4.0 perfection.

**Comment by yourfriendaaron** [comment]
Noticed another unthemed section, the popup when clicking on someone's name:

![2019-07-26 16 27 51](https://user-images.githubusercontent.com/8637082/61979650-6b496880-afc2-11e9-8d3c-48d226db64b3.png)

**Comment by LostConnection** [comment]
Ok, thanks guys. I Will try to implement a fix today.

**Comment by zwilson2** [comment]
I'm also having an issue with the "All Unreads" page. If there is channel text, that will be dark, but the rest of the screen is white:
![image](https://user-images.githubusercontent.com/17745598/62053547-d9ba4080-b1e5-11e9-89c2-089a15150dd6.png)

**Comment by defmonk0** [comment]
@LostConnection Are you doing something special to extract the CSS from darkreader for these fixes? I know you can easily grab a bunch of it using the method described [here](https://github.com/darkreader/darkreader/issues/604#issuecomment-406237559), but that doesn't necessarily get all of it.

Essentially, what I'm asking is If these windows fixes you've been doing are hand-edited, or if you have a way to properly extract them. If it's just hand-edited, I could probably PR fixes for these.

**Comment by LostConnection** [comment]
Hi, sorry for being late, I'm on holiday at the moment. The Windows changes were by hand. If you like you you can raise a PR...that would be a huge help as I'm not back until next week!

**Comment by defmonk0** [comment]
@LostConnection cool. I submitted it. #34
